# Generated by Django 4.2.16 on 2024-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('valor', models.FloatField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tablero',
                'verbose_name_plural': 'tableros',
                'ordering': ['-creado'],
                'permissions': (('es_miembro_1', 'Es miembro con prioridad 1'),),
            },
        ),
    ]
